# Repo Metadata:
product_name: Page Builder
component_name: Page Builder Types
team_name: Woke Owls
team_dl: Grp-woke-owls-team@adobe.com
jira_url: https://jira.magento.com/secure/RapidBoard.jspa?rapidView=2101
